[project]
name = "yabk-dump"
version = "0.4.1"
description = "Download and convert books from Yandex Books"

requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "pycookiecheat>=0.8.0",
    "pycryptodome>=3.23.0",
    "questionary>=2.1.1",
    "tqdm>=4.66.0",
    "yandex-book-api>=2.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
    "ty>=0.0.61",
]
[build-system]
requires = ["uv_build<=0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "yabk_dump"
module-root = "src"

[project.scripts]
yabk-dump = "yabk_dump.cli:run"
