[project]
name = "yabk-dump"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pycookiecheat>=0.8.0",
    "pycryptodome>=3.23.0",
    "questionary>=2.1.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]
[build-system]
requires = ["uv_build>=0.2.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "yabk_dump"
module-root = "src"

[project.scripts]
yabk-dump = "yabk_dump.cli:run"